spring:
    mail:
       host: smtp.163.com 
       password: fang0311 
       port: 25 
       protocol: smtp
       username: m17666292862@163.com
    application:
        name: EUREKAMAIL
eureka:
    client:
       serviceUrl:
          defaultZone: http://localhost:8761/eureka/ 
server:
    port: 8082